- name: remove file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: NGINX config file
  copy: src=files/magento_default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
