plugin: aws_ec2
regions:
  - us-east-1
boto_profile: "{{ lookup('env', 'AWS_PROFILE') | default('default', true) }}"
keyed_groups:
  - key: tags.Name
    separator: ''
hostnames:
  - network-interface.association.public-ip
